### ISSUE TITLE
atom.workspaceView deprecated (no longer available)

### ISSUE THREAD

**Issue by jesperronn** [omegahm/ruby-syntax-replacer#8]
Atom editor v 0.176 presents the following warning in the "deprecation cop" view:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/jesper/.atom/packages/ruby-syntax-replacer/lib/ruby-syntax-replacer.coffee:3:9)
```

I have not looked into the docs about fixing, just wanted to post here for anybody to work on it :)

**Comment by omegahm** [comment]
@jesperronn :+1: Thanks for the update.

As you can see on the commit history I haven't been updating it for quite a while (Last time was around July 2014).
I have meant to give it an overhaul (and possible write a spec or two) for some time, but haven't really gotten round to it yet.

Any day now... :dancers:
